blueprint:
  name: Climate Control Turn Off Notification Action
  description: Climate Control Turn Off Notification Action
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/eh_integration/raw/refs/heads/main/custom_components/effortlesshome/blueprints/automation/EffortlessHome/eh_climate_control_action.yaml
  input:
    target_climate:
      name: Climate Control Entity
      description: Choose the climate control entity(s) to manage.
      selector:
        entity:
          domain:
          - climate
          multiple: true

    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
        else.
      default: []
      selector:
        action: {}

trigger:
- platform: event
  event_type: mobile_app_notification_action
  event_data:
    action: TURNOFFCLIMATE

action:

- action: climate.turn_off
  metadata: {}
  data: {}
  target:
    entity_id: !input target_climate

- choose: []
  default: !input additional_actions

mode: single
