blueprint:
  name: Calendar Notifications & Actions
  description: Calendar Notifications & Actions
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/eh_integration/raw/refs/heads/main/custom_components/effortlesshome/blueprints/automation/EffortlessHome/eh_calendar-notifications-and-actions.yaml
  input:
    calendar:
      name: Calendar *
      description: Calendar to be used.
      default: {}
      selector:
        entity:
          filter:
          - domain:
            - calendar
          multiple: false
    global_conditions:
      name: Global Conditions
      description: Enter any global conditions you would like to apply to the automation.
      default: []
      selector:
        condition: {}
    additional_actions:
      name: Additional Actions
      description: Add any actions to execute (otional)
      default: []
      selector:
        action: {}
mode: single
trigger:
- platform: calendar
  event: start
  entity_id: !input calendar
  offset: 0:0:0
condition:
- condition: and
  conditions: !input global_conditions
action:
- choose: []
  default: !input additional_actions
