blueprint:
  name: Pool Water Quality Manager
  description: TBD
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/blueprints/raw/refs/heads/main/automation/EffortlessHome/eh_pool_waterquality_manager.yaml

  input:

    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}

trigger:
  - platform: time_pattern
    minutes: /1


action:

- choose: []
  default: !input additional_actions
mode: single
