blueprint:
  name: Smoke Alarm Triggered
  description: Set the actions to take when a smoke alarm is triggered
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/eh_integration/raw/refs/heads/main/custom_components/effortlesshome/blueprints/automation/EffortlessHome/eh_smokealarm.yaml
  input:
    smokealarm:
      name: Smoke Alarm Sensor
      description: The triggering smoke alarm sensor(s)
      selector:
        entity:
          filter:
          - domain:
            - binary_sensor
            - group
          multiple: true
    person_input:
        name: Person
        description: The person (or people) to notify
        selector:
            entity:
                multiple: true
                filter:
                    domain: person
    notification_message:
      name: Notification message
      description: Smoke Detector Activated Message
      default: Smoke Alarm Activated. Check for fire immediately.
    data_clickaction_url:
      name: URL to Navigate (Optional)
      description: The URL to navigate to when clicking on the notification. (default
        = /lovelace)
      default: /lovelace
    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}
trigger:
- platform: state
  entity_id: !input smokealarm
  to: 'on'
action:
- service: effortlesshome.notify_person_service
  data:
    target: !input person_input
    message: !input notification_message
    title: Smoke Alarm Activated
    data:
      clickAction: !input data_clickaction_url
      ttl: 0
      priority: high
      url: !input data_clickaction_url
- choose: []
  default: !input additional_actions
