blueprint:
  name: Temperature Alarm Triggered
  description: Set the actions to take when a temperature alarm is triggered
  domain: automation
  author: EffortlessHome
  source_url: https://github.com/EffortlessHome/eh_integration/raw/refs/heads/main/custom_components/effortlesshome/blueprints/automation/EffortlessHome/eh_temperature_alarm.yaml
  input:
    tempsensor:
      name: Temperature Sensor
      description: The triggering temperature sensor(s)
      selector:
        entity:
          filter:
          - domain:
            - sensor
          multiple: true
    low_trigger_temperature:
      description: Temperature to use to trigger a low temp alert
      name: Low temperature trigger
      default: 40
      selector:
        number:
          min: 0.0
          max: 60.0
          unit_of_measurement: degrees
          step: 1.0
          mode: slider
    high_trigger_temperature:
      description: Temperature to use to trigger a high temp alert
      name: High temperature trigger
      default: 85
      selector:
        number:
          min: 0.0
          max: 99.0
          unit_of_measurement: degrees
          step: 1.0
          mode: slider
    notification_message:
      name: Notification message
      description: 'Temperature Sensor Activated Message'
      default: 'Temperature Sensor Activated'

    data_clickaction_url:
      name: URL to Navigate (Optional)
      description: The URL to navigate to when clicking on the notification. (default
        = /lovelace)
      default: /lovelace

    additional_actions:
      name: Additional Actions
      description: Add additional actions to execute (Optional)
      default: []
      selector:
        action: {}
trigger:
- platform: numeric_state
  entity_id: !input tempsensor
  above: !input high_trigger_temperature
- platform: numeric_state
  entity_id: !input tempsensor
  below: !input low_trigger_temperature
variables:
  clickActionURL: !input data_clickaction_url

action:
- service: notify.notify
  data:
    title: Temperature Sensor Activated
    message: !input notification_message
    data:
      clickAction: !input data_clickaction_url
      ttl: 0
      priority: high
      url: !input data_clickaction_url

- choose: []
  default: !input additional_actions
