# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true
  packages: !include_dir_merge_named packages/


# https://www.home-assistant.io/integrations/logger/
logger:
  default: debug
  logs:
    custom_components.integration_EffortlessHome: debug

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

  # Example absolute path: /home/paulus/dev/hass/frontend
  development_repo: frontend

automation: !include automations.yaml
script: !include scripts.yaml
#scene: !include scenes.yaml

